### ISSUE TITLE
Cannot enter a Table No manually

### ISSUE THREAD

**Issue by fvet** [Drakonian/data-editor-for-bc#1]
When manually filling a Table No, it is not accepted.

![manual](https://user-images.githubusercontent.com/25268332/135105039-65da165e-c13c-4817-a572-c4cc47445ae2.gif)

The same occur when I would empty the Table No once selected from the '...'

**Comment by Drakonian** [comment]
Hi @fvet 
Thank you for reporting this problem, it has been fixed.
