### ISSUE TITLE
How to open

### ISSUE THREAD

**Issue by IridiumWasTaken** [Drakonian/data-editor-for-bc#11]
Hello,

how do I open the dialog to change table data? I installed the app, but I cannot find any pages, reports etc. when searching for "Data editor". If I try to open any of the pages (e.g. Page 81001) by appending ?page=81001, I get a permission error even though I am a super user.

**Comment by Drakonian** [comment]
Hi, could you specify your version of BC?

Also, try to add permission "Data Editor Tool" for your user

**Comment by IridiumWasTaken** [comment]
I copied the source code and compiled myself. The version is BC365 19, runtime 8.0. I changed to ID range to match the ID range that's licensed (changing your code).

**Comment by Drakonian** [comment]
I will say no, super should be enough. I think you made some mistakes when copied code and in id ranges.
Could you specify information about your license range and compiled project? Maybe I will find something

**Comment by IridiumWasTaken** [comment]
Ok I checked again and I made a stupid mistake regarding the ID range where I mistook it with another project. I changed the ID ranges accordingly again and now it works, so it's solved. Sorry for wasting your time! 
Your extension is really useful for testing, thanks a lot 😊
