### ISSUE TITLE
Can't update/delete warehouse entries

### ISSUE THREAD

**Issue by ashgibson** [Drakonian/data-editor-for-bc#17]
I keep getting a permission errors when trying to update or delete records in the warehouse entry table.

Sorry, the current permissions prevented the action. (TableData Warehouse Entry Modify: Data Editor Tool)

Sorry, the current permissions prevented the action. (TableData Warehouse Entry Delete: Data Editor Tool)

I am fully aware how destructive this might be and am just testing in a sandbox to see if it resolves the issue I am having with some corrupt data.

**Comment by Drakonian** [comment]
FIxed in last update.
