### ISSUE TITLE
Issue or Feature Request for Update Column

### ISSUE THREAD

**Issue by wikrie** [Drakonian/data-editor-for-bc#18]
Hi Volodymyr;

First Thank you for your great work, I really like your work.
I would like to ask you if the Action “Update Column” could be modify.
Because if I open a table and select only a part of it and then use the function it always run over all entries from the table. So could we include Filter criteria in the Action or could we use ONLY the current shown entries from the table?

It works as expected if I filter bevor loading the table but not after loading the table.
So this is more an issue than a feature request.

Thanks for your time and all the best

WiKrIe

**Comment by Drakonian** [comment]
Hello,
Thank you for your message. I agree that such behavior can cause confusion in use, I will address this.

**Comment by wikrie** [comment]
Hi Thanks for fast response, if I find some time for it, I will send you an proposal for the issue. Von meinem iPhone gesendetAm 14.07.2023 um 18:45 schrieb Volodymyr Dvernytskyi ***@***.***>:﻿
Closed #18 as completed.

**Comment by wikrie** [comment]
Oh it is already fixed wow that was fast. Von meinem iPhone gesendetAm 14.07.2023 um 22:15 schrieb Wikrie ***@***.***>:﻿Hi Thanks for fast response, if I find some time for it, I will send you an proposal for the issue. Von meinem iPhone gesendetAm 14.07.2023 um 18:45 schrieb Volodymyr Dvernytskyi ***@***.***>:﻿
Closed #18 as completed.
