### ISSUE TITLE
Feature Request and Update

### ISSUE THREAD

**Issue by wikrie** [Drakonian/data-editor-for-bc#19]
Hi Drakonian,

From my OnPrem Point of view:
I have update the permission to the base Page, so that only super user can use this page as it is to powerfull to be used by any normal user (maybe special Permission should be obsolete? ). So I add a trigger on init like this:
    trigger OnInit()
    var
        UserPermissions: Codeunit "User Permissions";
    begin
        if not UserPermissions.IsSuper(UserSecurityId()) then
            Error('Only Super User can load this please contact Admins.');
    end;

if you do not like the changes or think they are bad pelase simply clos the issue, as I cannot find a topic feature request I always open it under issue. 

br wikrie

**Comment by Drakonian** [comment]
Hi,

I agree with you, it's bad idea give everyone access to data editor.

Now only **Super** user or user with **Data Editor Tool** permission set will be able to use DataEditor

see:
https://github.com/Drakonian/data-editor-for-bc/commit/efe67d5089e3ecfdc617c1edf96a332a4e28af5b
