### ISSUE TITLE
Updating VAT Entry (table 254)

### ISSUE THREAD

**Issue by Francescobeatrice-bf** [Drakonian/data-editor-for-bc#20]
Hi,

first of all, thank you, this is an awesome application we've been using for a while with great satisfaction!
There's one case I can't seem to be able to modify data, i.e. Posting Date on table 254 (VAT Entry).
I get this message:

> Sorry, the current permissions prevented the action. (TableData VAT Entry Modify: Data Editor)

Is this a special table that can't be updated? Thank you in advance!

**Comment by wikrie** [comment]
for Table 254  we need a list of permission tables and in page 81000 there are 4 missing so please try to add

                    TableData "Service Invoice Header" = rmid,
                    TableData "Service Cr.Memo Header" = rmid,
                    TableData "Issued Reminder Header" = rmid,
                    TableData "Issued Fin. Charge Memo Header" = rmid,

and then it should work.

**Comment by Francescobeatrice-bf** [comment]
Thank you, I updated the file for page 81000 and it worked!

**Comment by Drakonian** [comment]
@Francescobeatrice-bf @wikrie 
Hey,

Thanks for reporting, master branch is also updated!
