### ISSUE TITLE
Insert into FA Ledger Entry

### ISSUE THREAD

**Issue by fzbeatrice** [Drakonian/data-editor-for-bc#21]
Hi,

I can edit all values in table 5601 (FA Ledger Entry) but I can't insert a new record into it.
I'm pretty dense about Business Central, so I thought I could add all permissions listed [here](https://learn.microsoft.com/en-us/dynamics365/business-central/application/base-application/codeunit/microsoft.fixedassets.ledger.fa-insert-ledger-entry) into Pag81000.DETDataEditorBuffer.al; these two

     tabledata "FA Ledger Entry", tabledata "Maintenance Ledger Entry" = RMID

were already there, so I added

    tabledata "FA Depreciation Book" = RIMD, tabledata "FA Register" = RIMD

I also added the following to PermissionSet81000.DETDataEditorTool.al

    table "FA Ledger Entry" = X,
    tabledata "FA Ledger Entry" = RIMD,
    page "FA Ledger Entries" = X,
    table "FA Depreciation Book" = X,
    tabledata "FA Depreciation Book" = RIMD,
    table "FA Register" = X,
    tabledata "FA Register" = RIMD,
    table "Maintenance Ledger Entry" = X,
    tabledata "Maintenance Ledger Entry" = RIMD;

to no avail.
What am I missing?

Thank you in advance!

Best regards

**Comment by Drakonian** [comment]
Hello,

This is your local issue regarding permissions.
Here is example of user setup where I am able to modify and insert new records in FA Ledger Entry. 
![image](https://github.com/Drakonian/data-editor-for-bc/assets/16802407/2eb0acf4-e692-4a3d-853c-835585588aee)

As you can see there is no SUPER permissions. Most likely your current user does not have Insert permissions to this table.

Look for an entry in your permissions that excludes permissions to insert a record into this table.

Tested on BC22.

@fzbeatrice

**Comment by fzbeatrice** [comment]
That might be the problem.
In the effective permissions page, I see that the insert permission is listed as Indirect (reduced) and when I click on it I get a weird message about licenses

![image](https://github.com/Drakonian/data-editor-for-bc/assets/99027831/05524339-b15c-42a5-8dc4-da9089eabcf6)

I don't get it, as my license are pretty normal:

![image](https://github.com/Drakonian/data-editor-for-bc/assets/99027831/69cffb8f-0abc-480e-9dd5-4d4dea870d16)

But I guess the problem lies elsewhere.

Again, thank you very much, Data Editor is an awesome tool!

Best regards
Francesco
