### ISSUE TITLE
Update column on decimal field

### ISSUE THREAD

**Issue by AlessandroLongoni** [Drakonian/data-editor-for-bc#22]
Hi,

if you try to use the function "Update column" on a decimal field, you can only use 2 decimal places instead of 5.
I tried it on field "Rounding precision" on item table and i had to update it from 1 to 0,00001 but i can only reach 0,01.

![image](https://github.com/Drakonian/data-editor-for-bc/assets/95044634/8eca8962-ecc9-419c-ba26-3179e7208bc2)

Thank you
Alessandro

**Comment by Drakonian** [comment]
Hello,

Thanks for letting me know, fix is already in the master branch for version 2.0.0.4

https://github.com/Drakonian/data-editor-for-bc/commit/b482ccbd622339b1bda5f6be3f3898bc61eaeafd

@AlessandroLongoni
