### ISSUE TITLE
Change PK in Table 114 Sales Cr.Memo Header

### ISSUE THREAD

**Issue by BrechtMarsoul** [Drakonian/data-editor-for-bc#24]
Hi, when I try to change the No. Field (PK) in the Table 114 Sales Cr.Memo Header, I get following error message:
_"Sorry, the current permissions prevented the action. (TableData 114 Sales Cr.Memo Header Modify: Data Editor Tool)"_

Is this a known limitation of the extension?

Awesome extension by the way!! :-)

**Comment by Drakonian** [comment]
Hi,

Thanks!

No, it's supposed to work.
Did you attach "DET DATA EDITOR TOOL" permission set for your user?
@BrechtMarsoul

**Comment by Drakonian** [comment]
Also, make sure that you use latest 2.0.0.6 version of extension

**Comment by BrechtMarsoul** [comment]
Hi,
Just checked and indeed latest 2.0.0.6 version of extension was installed. 
Also Permission Set and Licenses were assigned to my user.

When I try second time to change the No. Field (PK) in the Table 114 Sales Cr.Memo Header, I get following error message:
_"The binding of codeunit 81000 was unsuccessful. The codeunit has already been bound."_

See screenshots attached.
![Screenshot2](https://github.com/Drakonian/data-editor-for-bc/assets/164380782/c7d35ffd-daff-4f42-a9ff-22774c2033f8)
![Screenshot1](https://github.com/Drakonian/data-editor-for-bc/assets/164380782/bc708a48-905d-48fe-8a15-ee999de6d996)

**Comment by Drakonian** [comment]
@BrechtMarsoul 
I wonder if that's a different kind of error. It doesn't happen in my test. I assume you have some customization in your database that conflicts for Cr. Memo Header.

I have released a new version 2.0.0.8 which in theory should fix this particular new bug. Let me know the result of the test

**Comment by alopergolo** [comment]
Hello, i still had the problem even with the last update.
I solved it by adding permissions for the tables in the "DET Data Editor Mgt." codeunit.

Great extension!!

**Comment by Drakonian** [comment]
> Hello, i still had the problem even with the last update. I solved it by adding permissions for the tables in the "DET Data Editor Mgt." codeunit.
> 
> Great extension!!

I agree it's good idea to put permissions for this codeunit, nice catch, thanks!
https://github.com/Drakonian/data-editor-for-bc/commit/1c46f919b9f1cc3b2fa267670f91eae7c03926c4
