### ISSUE TITLE
Filter Table Data before loading into buffer

### ISSUE THREAD

**Issue by fvet** [Drakonian/data-editor-for-bc#3]
It seems to me that when specifying a table id on the Table Editor page request page, **all records** are loaded into DET Data Editor Buffer (81000, List). User can then apply filters once the buffer page is loaded. However, when the table id has lots of data in it, the buffer page seems to be really slow.

Wouldn't it be possible to apply filters up-front (using the RequestPageBuilder) to limit the no. of records to be loaded in the buffer and thus speed up performance? I can imagine if you need to update a value to one document / entry / ... only, it would be lots faster loading a single record instead of fetching all records.

Additionally, it would be nice to see a 'No. of Records' (count) after the table id / filters have been applied on the page request page (to inform / alert the users on the no. of records to be loaded into the buffer)

**Comment by Drakonian** [comment]
@fvet 
Great idea! Thanks for support!

Extensions is updated:
1.Possibility to filter record before loading. Just click on Table Filter field after Source Table No. selected
![image](https://user-images.githubusercontent.com/16802407/136481643-f244fa20-7919-49c0-b210-3277bc9ea315.png)

2.Number of Records - count of non/filtered records.
![image](https://user-images.githubusercontent.com/16802407/136481591-43ec5112-225f-4fc9-b2da-ca65f33d2968.png)
