### ISSUE TITLE
Date changed when importing data from Excel

### ISSUE THREAD

**Issue by johnbridgwater** [Drakonian/data-editor-for-bc#31]
Steps to reproduce:

- Export some data including date fields
- Import same data back with Modify on Find

Expected Results:
- Date is unchanged

Actual Results:
- All Date fields are changed by one day

Exported data:
<img width="828" alt="image" src="https://github.com/user-attachments/assets/a2713f47-df56-47c2-8959-f95b673b28dc">

Data Editor Log:
<img width="905" alt="image" src="https://github.com/user-attachments/assets/18612d0d-68c7-41b0-b818-fc32363413be">

**Comment by Drakonian** [comment]
Thanks, I'll look into the problem this week.

**Comment by Drakonian** [comment]
@johnbridgwater  should be fixed in last update
https://github.com/Drakonian/data-editor-for-bc/commit/e4d13ebc6af5e804a326d128f00358122fd5bf8c

**Comment by johnbridgwater** [comment]
Many thanks.

Best regards,

John Bridgwater
Business Process Principal
Office:  +44 (0) 121 378 7000
Mobile: +44 (0) 7815 520614
***@***.******@***.***>

***@***.***

From: Volodymyr Dvernytskyi ***@***.***>
Sent: Sunday, October 27, 2024 11:43 PM
To: Drakonian/data-editor-for-bc ***@***.***>
Cc: John Bridgwater ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [Drakonian/data-editor-for-bc] Date changed when importing data from Excel (Issue #31)

WARNING: This is an EXTERNAL email. THINK before you open attachments, click links or respond. USE the Outlook button to REPORT suspicious email.

Closed #31<https://github.com/Drakonian/data-editor-for-bc/issues/31> as completed.

-
