### ISSUE TITLE
Edit integer fields is not possible (BC19)

### ISSUE THREAD

**Issue by fvet** [Drakonian/data-editor-for-bc#4]
Running the latest version of your app on a BC 19 platform (in Edge), seems not to allow to edit non text/code fields.

I'm not able to update e.g. the 'Credit Limit (LCY)' of a customer record. Bug or am I doing something wrong?

![EditNumbers](https://user-images.githubusercontent.com/25268332/136368577-ba0b62db-efee-494e-beac-4f01bad42d87.gif)
.

Same for options, boolean, integers, decimals ...

**Comment by fvet** [comment]
@Drakonian Were you able to successfully edit options in a BC 19 setup?

**Comment by Drakonian** [comment]
@fvet Yes, Microsoft just broke the OnDrillDown trigger.
https://github.com/microsoft/AL/issues/6796

**Comment by Drakonian** [comment]
Fixed by Microsoft
