### ISSUE TITLE
OnValidateField to support more data types

### ISSUE THREAD

**Issue by fvet** [Drakonian/data-editor-for-bc#6]
Can we avoid the need to open an extra page for editing non text/code fields such as integer, decimals, dates?

If the `OnValidateField ` procedure would be able to **evaluate** the value based on the field's datatype, we could edit data directly via the buffer list page instead. (Similar to have attributes - supporting multiple data types - in BC are designed)

![image](https://user-images.githubusercontent.com/25268332/136371703-d5b6aef9-1b65-4ec5-8b34-ddba4bdc9a45.png)

**Comment by Drakonian** [comment]
@fvet 
This extra page is intentionally added to avoid problems with incorrect input formats. For example, the DateTime field will expect a specific input format depending on the regional settings. So, additional page helps to input data in correct data type format.
But I agree that you may have the choice to use the extra page or direct input. 

Support for such formats for direct input has been added:
**Integer, Decimal, Boolean, Date, DateFormula, DateTime, Time, Guid, BigInteger**
