### ISSUE TITLE
Set Value xx captions to Locked = true?

### ISSUE THREAD

**Issue by fvet** [Drakonian/data-editor-for-bc#7]
I'm considering translating the Data Editor and might add (Dutch) translations for all **relevant** fields / controls.

Some captions don't make sense to be translated, so might be interesting if they could be excluded from being translated by adding '**, Locked = true**'.

**Table Fields**
- Applies to all **Value xx** fields
- Caption = 'Value 2' 
- Caption is replaced by the CaptionClass / GetCaption, to the 'Value 2' does not really needs translation
- Caption = 'Value 2', Locked = true

**Page Fields**
- Applies to all **Value xx** fields
- ToolTip = 'Specifies the value of the Value 2 field';
- 'Value 2' makes no sense at all, so maybe the tooltip is redundant?

**Comment by Drakonian** [comment]
@fvet 
You can translate only those fields that make sense, for this it is not necessary to use exclude them from the main translation. Just add only required fields to new Translation File.

About tooltips:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0218

**Comment by fvet** [comment]
@Drakonian No problem, will perform the change in a separate branch.

Our internal pipeline policy is to have all labels / captions translated (except the Locked = true ones).
PS: We've also disabled AA0218 on purpose in our Add-on.
